version: "2"
services:
    wp:
        build: .
        ports:
            - "9005:80"
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=test
            - WORDPRESS_DB_PASSWORD=test
            - WORDPRESS_DB_NAME=wp

    db:
        image: mariadb
        environment:
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=wp
            - MYSQL_ROOT_PASSWORD=root
