---
apiVersion: skaffold/v3
kind: Config
profiles:
    - name: app
      build:
          local:
              push: true
          artifacts:
              - image: rkt-registry:5000/wordpress-hardened
                docker:
                    dockerfile: Dockerfile
          tagPolicy:
              gitCommit: {}
          insecureRegistries:
              - rkt-registry:5000
      deploy:
          statusCheck: true
          statusCheckDeadlineSeconds: 120
          helm:
              releases:
                  - name: wp
                    chartPath: helm/wordpress-hardened
                    recreatePods: true
                    namespace: wp
                    createNamespace: true
                    valuesFiles:
                        - skaffold.values.yaml
                    setValueTemplates:
                        image:
                            repository: rkt-registry:5000/wordpress-hardened
                            tag: '{{.IMAGE_TAG}}'

      portForward:
          - resourceType: service
            resourceName: wp-wph
            namespace: wp
            port: 80
            localPort: 8050


    - name: deps
      deploy:
          statusCheck: true
          statusCheckDeadlineSeconds: 120
          helm:
              releases:
                  - name: mariadb
                    repo: https://charts.bitnami.com/bitnami
                    version: 11.5.4
                    remoteChart: mariadb
                    namespace: db
                    createNamespace: true
                    wait: true
                    setValueTemplates:
                        fullnameOverride: mariadb
                        architecture: standalone
                        auth.rootPassword: "lgbt-1312"
                        auth.password: "lgbt-1312"
                        auth.database: "riotkit"
                        auth.username: "riotkit"

