---
apiVersion: skaffold/v3
kind: Config
profiles:
    - name: app
      build:
          local:
              push: true
          artifacts:
              - image: rkt-registry:5000/backup-repository
                ko:
                    dependencies:
                        paths: ["**/*.go", "go.mod", "go.sum"]
                        ignore: ["**/*_test.go"]
          tagPolicy:
              gitCommit: {}
          insecureRegistries:
              - rkt-registry:5000
      deploy:
          statusCheck: true
          statusCheckDeadlineSeconds: 120
          helm:
              releases:
                  - name: wp
                    chartPath: helm/backup-repository-server
                    recreatePods: true
                    namespace: backups
                    createNamespace: true
                    setValueTemplates:
                        db:
                            user: riotkit
                            name: riotkit
                            host: mariadb.db.svc.cluster.local
                            port: 3306
                            password:
                                secretName: db-credentials
                                secretKey: password

                        env:
                            HTTPS: off
                            WP_PREINSTALL: true

                        domain: "localhost"
                        publicPort: "8050"

                        health:
                            allowedSubnets: 0.0.0.0/0



      portForward:
          - resourceType: service
            resourceName: server-backup-repository-server
            namespace: wp
            port: 8080
            localPort: 8050


    - name: deps
      deploy:
          statusCheck: true
          statusCheckDeadlineSeconds: 120
          helm:
              releases:
                  - name: mariadb
                    repo: https://charts.bitnami.com/bitnami
                    version: 11.5.4
                    remoteChart: mariadb
                    namespace: db
                    createNamespace: true
                    wait: true
                    setValueTemplates:
                        fullnameOverride: mariadb
                        architecture: standalone
                        auth.rootPassword: "lgbt-1312"
                        auth.password: "lgbt-1312"
                        auth.database: "riotkit"
                        auth.username: "riotkit"

