{{- if .Values.backups.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: {{ include "wordpress-hardened.fullname" . }}-backup
spec:
    schedule: "{{ .Values.backups.schedule }}"
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: Never
                    containers:
                        - name: backup-maker
                          image: {{ .Values.backups.image.repository }}:{{ .Values.backups.image.tag }}
                          imagePullPolicy: Always
                          command:
                              - /bin/bash
                              - /usr/backup-maker/wp-filesystem-and-db-snapshot
                          envFrom:
                              - secretRef:
                                    name: {{ .Values.backups.secrets.name }}
                              - secretRef:
                                    name: {{ .Values.secrets.name }}
                          env:
                              {{- with .Values.backups.env }}
                              {{- range $key, $value := . }}
                              - name: {{ $key }}
                                value: "{{ $value }}"
                              {{- end }}
                              {{- end }}
                          volumeMounts:
                              - name: data
                                mountPath: /usr/backup-maker
                              - name: backup-secrets
                                mountPath: /mnt/backup-secrets
                              {{- if .Values.pv.wp.enabled }}
                              - name: wp
                                mountPath: /var/www/riotkit
                              {{- end }}
                              - name: wp-content
                                mountPath: /var/www/riotkit/wp-content

                    volumes:
                        - name: data
                          configMap:
                              name: {{ include "wordpress-hardened.fullname" . }}-backups-config
                        - name: backup-secrets
                          secret:
                              secretName: {{ .Values.backups.secrets.name }}
                              optional: false
                        - name: wordpress-secrets
                          secret:
                              secretName: {{ .Values.secrets.name }}
                              optional: false
                        {{- if .Values.pv.wp.enabled }}
                        - name: wp
                          persistentVolumeClaim:
                              claimName: {{ .Values.pv.wp.claimName }}
                        {{- end }}
                        - name: wp-content
                          persistentVolumeClaim:
                              claimName: {{ .Values.pv.wp_content.claimName }}

{{- end }}
