{{ range $jobName, $job := .Values.db.administrativeJobs }}
{{ if and $job.isHelmHook (not $job.schedule) }}
---
apiVersion: batch/v1
kind: Job
metadata:
    name: {{ $jobName }}
    labels:
        {{- include "wordpress-hardened.labels" $ | nindent 8 }}
    annotations:
        "helm.sh/hook": post-install
        "helm.sh/hook-delete-policy": before-hook-creation
spec:
    {{ $context := dict "Values" $.Values "Release" $.Release "Chart" $.Chart "job" $job "jobName" $jobName }}
    {{ include "wordpress-hardened.job" $context | nindent 4 }}
{{ end }}
{{ end }}
