{{ if .Values.db.administrativeJobs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "wordpress-hardened.name" . }}-sql-scripts
data:
    {{ range $jobName, $job := .Values.db.administrativeJobs }}
    {{ $jobName }}: |
        {{ $job.sql | nindent 8 }}
    {{ end }}
{{ end }}
