---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "wordpress-hardened.fullname" . }}
    labels:
        {{- include "wordpress-hardened.labels" . | nindent 8 }}
spec:
    replicas: {{ .Values.replicas }}
    revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
    selector:
        matchLabels:
            {{- include "wordpress-hardened.selectorLabels" . | nindent 10 }}

    {{- if .Values.rollingUpdate.enabled }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            {{ toYaml .Values.rollingUpdate.spec | nindent 12 }}
    {{- end }}

    template:
        metadata:
          {{- with .Values.podAnnotations }}
            annotations:
              {{- toYaml . | nindent 16 }}
          {{- end }}
            labels:
                {{- include "wordpress-hardened.selectorLabels" . | nindent 16 }}
                {{- if eq (.Values.image.tag | default .Chart.AppVersion) "latest" | or (eq (.Values.image.tag | default .Chart.AppVersion) "snapshot") }}
                refreshImageTag: "{{- randAlphaNum 24 | nospace -}}"
                {{- end }}
                {{- with .Values.podLabels }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- if .Values.volumeSyncing.enabled }}
                riotkit.org/volume-syncing-controller: true
                {{- end }}
        spec:
            automountServiceAccountToken: false
            terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default "5" }}
            {{- with .Values.podSecurityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
                {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
                {{- toYaml . | nindent 14 }}
            {{- end }}
            containers:
                {{- if .Values.waf.enabled }}
                - name: waf-proxy
                  image: {{ .Values.waf.image.repository }}:{{ .Values.waf.image.tag }}
                  imagePullPolicy: Always
                  env:
                      - name: CADDY_PORT
                        value: "8090"

                      {{- range $num, $ingress := $.Values.ingresses }}
                      {{- range $ingress.hosts }}
                      - name: UPSTREAM_{{ $num }}
                        value: '{"pass_to": "http://127.0.0.1:8080", "hostname": "{{ .host }}"}'
                      {{- end }}
                      {{- end }}

                      {{- with .Values.waf.env }}
                      {{- range $key, $value := . }}
                      - name: {{ $key }}
                        value: "{{ $value }}"
                      {{- end }}
                      {{- end }}

                  volumeMounts:
                      # allows to add extra directives
                      - name: waf-custom-config
                        mountPath: /etc/caddy/rules/custom.conf
                        subPath: custom.conf

                  ports:
                      - name: http-waf
                        containerPort: 8090
                        protocol: TCP

                      - name: waf-metrics
                        containerPort: 2019
                        protocol: TCP

                      - name: waf-healthcheck
                        containerPort: 8081
                        protocol: TCP

                  {{- if .Values.waf.health.liveness.enabled }}
                  livenessProbe:
                      {{- with .Values.waf.health.liveness.attributes}}
                      {{- toYaml . | nindent 22 }}
                      {{- end}}
                      httpGet:
                          path: /
                          scheme: HTTP
                          port: waf-healthcheck
                  {{- end }}
                {{- end }}

                - name: app
                  image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
                  imagePullPolicy: Always
                  env:
                      {{- with .Values.env }}
                      {{- range $key, $value := . }}
                      - name: {{ $key }}
                        value: "{{ $value }}"
                      {{- end }}
                      {{- end }}
                      - name: WORDPRESS_DB_NAME
                        value: {{ .Values.db.name | quote }}
                      - name: WORDPRESS_DB_USER
                        value: {{ .Values.db.user | quote }}
                      - name: WORDPRESS_DB_PORT
                        value: {{ .Values.db.port | quote }}
                      - name: WORDPRESS_DB_HOST
                        value: {{ .Values.db.host | quote }}
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.db.password.secretName | quote }}
                                key: {{ .Values.db.password.secretKey | quote }}

                  {{ if .Values.secrets.enabled }}
                  envFrom:
                      - secretRef:
                            optional: true
                            name: {{ .Values.secrets.name }}
                  {{ end }}
                  securityContext:
                      allowPrivilegeEscalation: false
                      runAsNonRoot: true
                  volumeMounts:
                      {{- if .Values.pv.wp.enabled }}
                      - name: wp
                        mountPath: /var/www/riotkit
                      {{- end }}
                      {{- if .Values.pv.wp_content.enabled }}
                      - name: wp-content
                        mountPath: /var/www/riotkit/wp-content
                      {{- end }}
                      {{- with .Values.pv.extraVolumeMounts }}
                      {{- toYaml . | nindent 22 }}
                      {{- end }}
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                  {{- if .Values.health.liveness.enabled }}
                  livenessProbe:
                      {{- with .Values.health.liveness.attributes}}
                      {{- toYaml . | nindent 22 }}
                      {{- end}}
                      httpGet:
                          path: /liveness.php
                          scheme: HTTP
                          port: http
                  {{- end }}
                  {{- if .Values.health.readiness.enabled }}
                  readinessProbe:
                      {{- with .Values.health.readiness.attributes }}
                      {{- toYaml . | nindent 22 }}
                      {{- end }}
                      httpGet:
                          path: /readiness.php
                          scheme: HTTP
                          port: http
                  {{- end }}
                  startupProbe:
                      httpGet:
                          path: /liveness.php
                          scheme: HTTP
                          port: http
                      failureThreshold: 10
                      periodSeconds: 5
                  resources:
                      {{- toYaml .Values.resources | nindent 20 }}
            volumes:
                {{- if .Values.pv.wp.enabled }}
                - name: wp
                  persistentVolumeClaim:
                      claimName: {{ .Values.pv.wp.claimName }}
                {{- end }}
                {{- if .Values.pv.wp_content.enabled }}
                - name: wp-content
                  persistentVolumeClaim:
                      claimName: {{ .Values.pv.wp_content.claimName }}
                {{- end }}
                {{- if .Values.waf.enabled }}
                - name: waf-custom-config
                  configMap:
                      name: {{ include "wordpress-hardened.fullname" . }}-waf-custom-config
                {{- end }}
                {{- with .Values.pv.extraVolumes }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
