{{- range $num, $ingress := $.Values.ingresses }}
{{- $fullName := include "wordpress-hardened.fullname" $ }}

---
  {{ $svcPort := $.Values.service.port -}}
  {{ if and $ingress.className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{ if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{ $_ := set $ingress.annotations "kubernetes.io/ingress.class" $ingress.className}}
  {{ end }}
  {{ end }}
  {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
    name: {{ .name }}
    labels:
      {{- include "wordpress-hardened.labels" $ | nindent 6 }}
  {{- with $ingress.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  {{- if and (and $ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) $ingress.className }}
    ingressClassName: {{ $ingress.className }}
  {{- end }}
  {{- if $ingress.tls }}
    tls:
      {{- range $ingress.tls }}
        - hosts:
            {{- range .hosts }}
              - {{ . | quote }}
            {{- end }}
          {{- if .secretName }}
          secretName: {{ .secretName }}
          {{- end }}
      {{- end }}
  {{- end }}
    rules:
      {{- range $ingress.hosts }}
        - host: {{ .host | quote }}
          http:
              paths:
                {{- range .paths }}
                  - path: {{ .path }}
                    {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
                    pathType: {{ .pathType }}
                    {{- end }}
                    backend:
                      {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
                        service:
                            name: {{ if $.Values.waf.enabled }}{{ $fullName }}-waf-protected{{ else }}{ $fullName }}{{ end }}
                            port:
                                number: 80
                      {{- else }}
                        serviceName: {{ if $.Values.waf.enabled }}{{ $fullName }}-waf-protected{{ else }}{ $fullName }}{{ end }}
                        servicePort: 80
                      {{- end }}
                {{- end }}
      {{- end }}

{{- end }}
