{{- range $num, $ingress := $.Values.ingresses }}
{{- $fullName := include "wordpress-hardened.fullname" $ }}

---
  {{ $svcPort := $.Values.service.port -}}
  {{ if $ingress.className }}
  {{ if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{ $_ := set $ingress.annotations "kubernetes.io/ingress.class" $ingress.className}}
  {{ end }}
  {{ end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .name | default $fullName }}
    labels:
      {{- include "wordpress-hardened.labels" $ | nindent 6 }}
  {{- with $ingress.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  {{- if and $ingress.className (not (hasKey $ingress.annotations "kubernetes.io/ingress.class")) }}
    ingressClassName: {{ $ingress.className }}
  {{- end }}
  {{- if $ingress.tls }}
    tls:
      {{- range $ingress.tls }}
        - hosts:
            {{- if or (not (hasKey . "hosts")) (not .hosts) }}
              - {{ $.Values.wordpress.domain | quote }}
            {{ else }}
            {{- range .hosts }}
              - {{ . | quote }}
            {{- end }}
            {{ end }}
          secretName: {{ .secretName | default $fullName }}
      {{- end }}
  {{- end }}
    rules:
      {{- range $ingress.hosts }}
        - host: {{ default $.Values.wordpress.domain .host | quote }}
          http:
              paths:
                {{- range .paths }}
                  - path: {{ .path }}
                    {{- if .pathType }}
                    pathType: {{ .pathType }}
                    {{- end }}
                    backend:
                        service:
                            name: {{ if $.Values.waf.enabled }}{{ $fullName }}-waf-protected{{ else }}{{ $fullName }}{{ end }}
                            port:
                                number: 80
                {{- end }}
      {{- end }}

{{- end }}
