{{ if .Values.backups.enabled }}
---
apiVersion: riotkit.org/v1alpha1
kind: ScheduledBackup
metadata:
    name: {{ include "wordpress-hardened.fullname" . }}
    labels:
        {{- include "wordpress-hardened.labels" . | nindent 8 }}
spec:
    collectionId: {{ .Values.backups.collectionId | quote }}
    cronJob:
        enabled: true
        scheduleEvery: {{ .Values.backups.schedule | quote }}
    gpgKeySecretRef:
        createIfNotExists: {{ .Values.backups.secrets.gpgKeys.createIfNotExists }}
        email: {{ .Values.backups.email | quote }}
        passphraseKey: passphrase
        privateKey: private
        publicKey: public
        secretName: {{ (default (printf "%s-gpg" (include "wordpress-hardened.fullname" .)) .Values.backups.secrets.gpgKeys.secretName) | quote }}
    operation: backup
    templateRef:
        kind: {{ .Values.backups.templateType }}
        name: {{ .Values.backups.templateName }}
    tokenSecretRef:
        secretName: {{ (default .Values.secrets.name .Values.backups.secrets.loginToken.secretName) | quote }}
        tokenKey: {{ .Values.backups.secrets.loginToken.secretKey | quote }}

    # =================================================================================
    # Docs: https://github.com/riotkit-org/br-backup-maker/tree/main/generate/templates
    # See backup type: wordpress-mariadb-x.y
    # =================================================================================
    vars: |
        Params:
          hostname: {{ .Values.db.host | quote }}
          port: {{ .Values.db.port | quote }}
          db: {{ .Values.db.name | quote }}
          user: {{ .Values.db.user | quote }}
          password: "${DB_PASSWORD}"

        Repository:
          url: {{ .Values.backups.url | quote }}
          recipient: {{ .Values.backups.email | quote }}
          collectionId: {{ .Values.backups.collectionId | quote }}
          passphrase: ""

        HelmValues:
          workspaceVolume:
            size: "256M"
            medium: Memory

          extraVolumes:
            - name: wordpress-pv
              persistentVolumeClaim:
                  claimName: {{ .Values.pv.wp_content.claimName | quote }}

          extraEnv:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretName | quote }}
                  key: {{ .Values.db.password.secretKey | quote }}
    varsSecretRef:
        importOnlyKeys: []
{{ end }}
