{{- if .Values.secrets.create }}
---
apiVersion: {{ .Values.secrets.apiVersion }}
kind: {{ .Values.secrets.kind }}
metadata:
    name: {{ .Values.secrets.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        {{- include "wordpress-hardened.labels" . | nindent 8 }}
{{ .Values.secrets.content }}
{{- end }}
