---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "wordpress-hardened.fullname" . }}
    labels:
        {{- include "wordpress-hardened.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ if .Values.waf.enabled }}8090{{ else }}8080{{ end }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        {{- include "wordpress-hardened.selectorLabels" . | nindent 8 }}
