image:
    repository: ghcr.io/riotkit-org/wordpress-hardened
    tag: "" # defaults to {{ .Release.appVersion }}

terminationGracePeriodSeconds: 20
revisionHistoryLimit: 1

podSecurityContext:
    runAsUser: 65161
    runAsGroup: 65161
    fsGroup: 65161
podDisruptionBudget:
    enabled: false
    spec:
        minAvailable: 1
        maxUnavailable: 0
replicas: 1
rollingUpdate:
    enabled: true
    spec:
        maxSurge: 1
        maxUnavailable: 0

extraConfigMaps: []

db:
    user: wordpress
    name: wordpress
    host: mariadb.db.svc.cluster.local
    port: 3306
    password:
        secretName: db-credentials
        secretKey: password

wordpress:
    # -- Should the WordPress automatically update itself periodically? NOTICE! Use with .pv.wp.enabled = true
    autoUpdate: true

pv:
    # -- Disable whole root directory volume to have WordPress version managed by the container. Enable it to use updater from the web - in this case the image version would only matter for PHP, NGINX versions, but the WordPress version would be bumped by WordPress by his own
    wp:
        enabled: true
        create: true
        claimName: wp
        size: 256Mi
        #storageClassName: "..."

    # [!!!] Disabling persistence on wp-content may be dangerous, better know what you are doing
    wp_content:
        enabled: true
        claimName: wp-content
        create: true
        size: 1Gi
        #storageClassName: "..."

    # use those following to e.g. mount a custom ConfigMap, or a PVC with some data
    extraVolumes: []
    extraVolumeMounts: []


ingresses: []
#    - name: wp-https
#      className: nginx
#      annotations:
#          cert-manager.io/cluster-issuer: letsencrypt-staging
#      hosts:
#          - host: example.org
#            paths:
#                - path: /
#                  pathType: ImplementationSpecific
#      tls:
#          - hosts: ["example.org"]
#            secretName: wp-tls

# environment variables passed to the container - see Dockerfile and https://github.com/riotkit-org/wordpress-hardened for reference
env:
    HTTPS: "on"
    WP_PAGE_URL: "https://my-page.org"
    HEALTH_CHECK_ALLOWED_SUBNET: "10.0.0.0/8"   # type your POD CIDR there or explicit control plane IP address

# -- Allows to embed `kind: Secret`, `kind: SealedSecret`, `kind: ExternalSecret` or any other secret. Use it for example with Bitnami's Sealed Secret
secrets:
    name: wordpress-secrets
    create: false
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    content: |
        encryptedData:
            ...

resources:
    requests:
        memory: 16Mi
        cpu: 0
    limits:
        memory: 128Mi
        cpu: 1

health:
    liveness:
        enabled: true
        attributes:
            failureThreshold: 2
            periodSeconds: 60
    readiness:
        enabled: true
        attributes:
            failureThreshold: 2
            periodSeconds: 60

service:
    type: ClusterIP
    port: 8080

# =====================================================================
# Web Application Firewall - protects your WP instance against attacks
# Requires Ingress to be created.
# =====================================================================
waf:
    enabled: false
    image:
        repository: ghcr.io/riotkit-org/waf-proxy
        tag: snapshot
    env:
        ENABLE_RULE_WORDPRESS: true
        ENABLE_CRS: true
        ENABLE_RATE_LIMITER: true
        RATE_LIMIT_EVENTS: "30"
        RATE_LIMIT_WINDOW: "5s"

        # due to bug temporarily the CORAZA WAF is disabled, it will be enabled by default in future releases
        ENABLE_CORAZA_WAF: false

    directives: |
        #SecDefaultAction "phase:4,allow,log"
        #SecAction "id:1,pass,log"
        #SecAuditLog /dev/stdout
        #SecDebugLog /dev/stdout
        #SecDebugLogLevel 5
    health:
        liveness:
            enabled: true
            attributes:
                failureThreshold: 2
                periodSeconds: 60

# =====================================================================
# Backup Repository integration
#
# Docs:
#   - Client: https://github.com/riotkit-org/br-backup-maker
#   - Client's controller: https://github.com/riotkit-org/backup-maker-controller
#   - Server: https://github.com/riotkit-org/backup-repository
# =====================================================================
backups:
    enabled: false

    # -- Crontab-like syntax, will be used in a `kind: CronJob` object
    schedule: "16 1 * * *" # 01:16 in the night

    # -- Backup Repository instance URL
    url: https://my-backup-repository-instance.org

    # -- Server side collection id (a backup slot/directory)
    collectionId: ""

    # -- Use MariaDB template version matching your server's version for best compatibility
    templateName: wordpress-mariadb-10.10
    templateType: internal

    # -- Used for GPG encryption. Recommended: Set the same as in user account in Backup Repository
    email: example@example.org

    secrets:
        # -- Login token is a JWT token generated by logging in to Backup Repository (see: https://github.com/riotkit-org/backup-repository/blob/767707ada71781a59b583f3e35f22618cf7c1e44/docs/api/users/README.md#post-apistableauthlogin)
        loginToken:
            secretName: backups-login
            secretKey: backup-login-token

        # -- GPG key pair - public & private key used for backup encryption. Will generate automatically if not present (make sure to back up created `kind: Secret`)
        gpgKeys:
            createIfNotExists: true
            secretName: backups-gpg
