image:
    repository: ghcr.io/riotkit-org/wordpress-hardened
    tag: "" # defaults to {{ .Release.appVersion }}

podSecurityContext:
    runAsUser: 65161
    runAsGroup: 65161
    fsGroup: 65161

pv:
    wp:
        enabled: true
        create: true
        claimName: wp
        size: 256Mi
        #storageClassName: "..."
    wp_content:
        claimName: wp-content
        create: true
        size: 1Gi
        #storageClassName: "..."


ingress:
    enabled: true
    hosts: ["my-page.org"]
    # className: nginx
    #secretName: ...
    tls:
        #hosts: ["my-page.org"]

env:
    HTTPS: "on"
    WP_PAGE_URL: "https://my-page.org"

secrets:
    name: wordpress-secrets
    content: |
        ---
        apiVersion: v1
        kind: Secret
        metadata:
            name: wordpress-secrets
        stringData:
            AUTH_KEY: change-me
            SECURE_AUTH_KEY: change-me
            LOGGED_IN_KEY: change-me
            NONCE_KEY: change-me
            AUTH_SALT: change-me
            SECURE_AUTH_SALT: change-me
            LOGGED_IN_SALT: change-me
            NONCE_SALT: change-me
        
            WORDPRESS_DB_NAME: "wordpress"
            WORDPRESS_DB_USER: "wordpress"
            WORDPRESS_DB_PASSWORD: "secret"
            WORDPRESS_DB_HOST: "mariadb.db.svc.cluster.local"

resources:
    requests:
        memory: 16Mi
        cpu: 0
    limits:
        memory: 128Mi
        cpu: 1

health:
    liveness:
        enabled: true
        attributes:
            failureThreshold: 1
            terminationGracePeriodSeconds: 10
    readiness:
        enabled: true
        attributes: {}

service:
    type: ClusterIP
    port: 8080
