image:
    repository: ghcr.io/riotkit-org/wordpress-hardened
    tag: "" # defaults to {{ .Release.appVersion }}

terminationGracePeriodSeconds: 20
revisionHistoryLimit: 1

podSecurityContext:
    runAsUser: 65161
    runAsGroup: 65161
    fsGroup: 65161
podDisruptionBudget:
    enabled: false
    spec:
        minAvailable: 1
        maxUnavailable: 0
replicas: 1
rollingUpdate:
    enabled: true
    spec:
        maxSurge: 1
        maxUnavailable: 0

extraConfigMaps: []

pv:
    wp:
        enabled: true
        create: true
        claimName: wp
        size: 256Mi
        #storageClassName: "..."

    # [!!!] Disabling persistence on wp-content may be dangerous, better know what you are doing
    #       Advanced usage: Store everything in S3 instead of in wp-content, then disable persistent volume and make WordPress a bit more stateless
    wp_content:
        enabled: true
        claimName: wp-content
        create: true
        size: 1Gi
        #storageClassName: "..."

    # use those following to e.g. mount a custom ConfigMap, or a PVC with some data
    extraVolumes: []
    extraVolumeMounts: []


ingresses: []
#    - name: wp-https
#      className: nginx
#      annotations:
#          cert-manager.io/cluster-issuer: letsencrypt-staging
#      hosts:
#          - host: example.org
#            paths:
#                - path: /
#                  pathType: ImplementationSpecific
#      tls:
#          - hosts: ["example.org"]
#            secretName: wp-tls

# environment variables passed to the container - see Dockerfile and https://github.com/riotkit-org/wordpress-hardened for reference
env:
    HTTPS: "on"
    WP_PAGE_URL: "https://my-page.org"
    HEALTH_CHECK_ALLOWED_SUBNET: "10.0.0.0/8"   # type your POD CIDR there or explicit control plane IP address

# allows to embed `kind: Secret`, `kind: SealedSecret`, `kind: ExternalSecret` or any other secret
secrets:
    name: wordpress-secrets
    create: true

    apiVersion: v1
    kind: Secret
    content: |
        stringData:
            AUTH_KEY: change-me
            SECURE_AUTH_KEY: change-me
            LOGGED_IN_KEY: change-me
            NONCE_KEY: change-me
            AUTH_SALT: change-me
            SECURE_AUTH_SALT: change-me
            LOGGED_IN_SALT: change-me
            NONCE_SALT: change-me
        
            WORDPRESS_DB_NAME: "wordpress"
            WORDPRESS_DB_USER: "wordpress"
            WORDPRESS_DB_PASSWORD: "secret"
            WORDPRESS_DB_HOST: "mariadb.db.svc.cluster.local"

resources:
    requests:
        memory: 16Mi
        cpu: 0
    limits:
        memory: 128Mi
        cpu: 1

health:
    liveness:
        enabled: true
        attributes:
            failureThreshold: 2
            periodSeconds: 60
    readiness:
        enabled: true
        attributes:
            failureThreshold: 2
            periodSeconds: 60

service:
    type: ClusterIP
    port: 8080

# =====================================================================
# Web Application Firewall - protects your WP instance against attacks
# Requires Ingress to be created.
# =====================================================================
waf:
    enabled: false
    image:
        repository: ghcr.io/riotkit-org/waf-proxy
        tag: snapshot
    env:
        ENABLE_RULE_WORDPRESS: true
        ENABLE_CRS: true
        ENABLE_RATE_LIMITER: true
        RATE_LIMIT_EVENTS: "30"
        RATE_LIMIT_WINDOW: "5s"

        # due to bug temporarily the CORAZA WAF is disabled, it will be enabled by default in future releases
        ENABLE_CORAZA_WAF: false

    directives: |
        #SecDefaultAction "phase:4,allow,log"
        #SecAction "id:1,pass,log"
        #SecAuditLog /dev/stdout
        #SecDebugLog /dev/stdout
        #SecDebugLogLevel 5
    health:
        liveness:
            enabled: true
            attributes:
                failureThreshold: 2
                periodSeconds: 60

# =====================================================================
# Backup Repository integration
#
# Docs:
#   - Client: https://github.com/riotkit-org/br-backup-maker
#   - Server: https://github.com/riotkit-org/backup-repository
# =====================================================================
backups:
    enabled: false
    schedule: "16 1 * * *" # 01:16 in the night
    image:
        repository: ghcr.io/riotkit-org/backup-maker
        tag: snapshot
    env:
        BACKUP_SERVER_URL: "https://backups.example.org"
        BACKUP_COLLECTION_ID: "111-222-333-444"
    secrets:
        create: true
        apiVersion: v1
        kind: Secret
        name: wp-backup
        content: |
            stringData:
                BACKUP_TOKEN: "..."  # JWT token here
                BACKUP_GPG_PASSPHRASE: "..."
                BACKUP_GPG_PRIVATE_KEY_CONTENT: |
                    -----BEGIN PGP PRIVATE KEY BLOCK-----
                    ...
                    -----END PGP PRIVATE KEY BLOCK-----
            
                # NOTICE: This must match your GPG key owner
                BACKUP_GPG_RECIPIENT: "example@example.org"
