name: Test and release
on:
    push:
    workflow_dispatch:
        inputs: {}

jobs:
    container-image:
        uses: riotkit-org/.github/.github/workflows/release.container.yaml@release-1
        with:
            osVariant: ubuntu-22.04
            intermediateArtifactsPath: ""
            dockerImage: "ghcr.io/riotkit-org/wordpress-hardened"

    helm:
        uses: riotkit-org/.github/.github/workflows/release.helm.yaml@release-1
        needs: ["container-image"]
        with:
            chartPath: helm/wordpress-hardened
            chartRepoName: "riotkit-org/charts/"
            chartName: wordpress-hardened

    test:
        uses: riotkit-org/.github/.github/workflows/test.integration-tests.yaml@release-1
        with:
            osVariant: ubuntu-22.04
            pythonEnabled: true
            testReportEnabled: true
            testReportPattern: kuttl-report.xml
