name: Test and release
on:
    push:
    workflow_dispatch:
        inputs: {}

jobs:
    container-image:
        uses: riotkit-org/.github/.github/workflows/release.container.yaml@release-1
        with:
            osVariant: ubuntu-22.04
            intermediateArtifactsPath: ""
            dockerImage: "ghcr.io/riotkit-org/wordpress-hardened"

    # todo: test on k3s

    helm:
        uses: riotkit-org/.github/.github/workflows/release.helm.yaml@release-1
        needs: ["container-image"]
        with:
            chartPath: charts/wordpress-hardened
            chartRepoName: "riotkit-org/charts/"
            chartName: wordpress-hardened
